### ISSUE TITLE
Funktion `wuerfeln()` sollte eine Wert zurückgeben

### ISSUE THREAD

**Issue by MatusGasparik** [MarionObrist/UebungenHS2022#2]
https://github.com/MarionObrist/UebungenHS2022/blob/673a40b9607a7ea8466e045ad43c262eca7bb193/Uebung02/Aufgabe02.js#L3-L6

## TODOs
- den Wert der Zufallsnummer aus der Funktion zurückgeben (mit `return`)
- kann man sich das `+ 1` sparen? Wie würde die Funktion aussehen?

**Comment by MarionObrist** [comment]
Das mit return habe ich herausgefunden. 
Beim +1 habe ich herausgefunden, dass wenn ich es weglasse, wird auch NULL als Wert akzeptiert. Daher glaube ich braucht es das +1. So gibt es nur die Werte 1-6 raus.

**Comment by MatusGasparik** [comment]
> Beim +1 habe ich herausgefunden, dass wenn ich es weglasse, wird auch NULL als Wert akzeptiert. Daher glaube ich braucht es das +1. So gibt es nur die Werte 1-6 raus. 

Wie wäre es mit `Math.ceil()`? :-)
